# Generated by Django 4.1.1 on 2022-10-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_e',
            name='cut_COD',
            field=models.IntegerField(default='0', verbose_name='减排COD量(万吨)'),
        ),
        migrations.AddField(
            model_name='company_e',
            name='cut_NO',
            field=models.IntegerField(default='0', verbose_name='减排氮氧化合物量(万吨)'),
        ),
        migrations.AddField(
            model_name='company_e',
            name='cut_andan',
            field=models.IntegerField(default='0', verbose_name='减排氨氮量(万吨)'),
        ),
        migrations.AddField(
            model_name='company_e',
            name='cut_co2',
            field=models.IntegerField(default='0', verbose_name='减排二氧化碳量(万吨)'),
        ),
        migrations.AddField(
            model_name='company_e',
            name='cut_so2',
            field=models.IntegerField(default='0', verbose_name='减排二氧化硫量(万吨)'),
        ),
        migrations.AddField(
            model_name='company_e',
            name='cut_water',
            field=models.IntegerField(default='0', verbose_name='节水量(万吨)'),
        ),
        migrations.AddField(
            model_name='company_e',
            name='oil_waste',
            field=models.IntegerField(default='0', verbose_name='油耗量(升)'),
        ),
        migrations.AddField(
            model_name='company_e',
            name='paper_waste',
            field=models.IntegerField(default='0', verbose_name='耗纸量(吨)'),
        ),
        migrations.AddField(
            model_name='company_e',
            name='save_coal',
            field=models.IntegerField(default='0', verbose_name='节约标准煤量(万吨)'),
        ),
        migrations.AddField(
            model_name='company_g',
            name='date',
            field=models.IntegerField(default='2022', max_length=4, verbose_name='信息年份'),
        ),
        migrations.AddField(
            model_name='company_g',
            name='pure_value',
            field=models.IntegerField(default='0', verbose_name='净利润(亿元)'),
        ),
        migrations.AddField(
            model_name='company_g',
            name='tax',
            field=models.IntegerField(default='0', verbose_name='纳税额(亿元)'),
        ),
        migrations.AddField(
            model_name='company_s',
            name='date',
            field=models.IntegerField(default='2022', max_length=4, verbose_name='信息年份'),
        ),
        migrations.AddField(
            model_name='company_s',
            name='donate',
            field=models.IntegerField(default='0', verbose_name='公益慈善投入(万元)'),
        ),
        migrations.AddField(
            model_name='company_s',
            name='female',
            field=models.IntegerField(default='0', verbose_name='女性员工占比(%)'),
        ),
        migrations.AddField(
            model_name='company_s',
            name='gupiao',
            field=models.IntegerField(default='0', verbose_name='每股社会贡献值(元)'),
        ),
        migrations.AddField(
            model_name='company_s',
            name='puhui',
            field=models.IntegerField(default='0', verbose_name='普惠贷款余额(亿元)'),
        ),
        migrations.AddField(
            model_name='company_s',
            name='shenong',
            field=models.IntegerField(default='0', verbose_name='涉农贷款(亿元)'),
        ),
        migrations.AddField(
            model_name='company_s',
            name='workers',
            field=models.IntegerField(default='0', verbose_name='总员工数量(人)'),
        ),
        migrations.AlterField(
            model_name='company_e',
            name='Energy_consumption',
            field=models.IntegerField(default='0', verbose_name='电消耗量(千瓦时)'),
        ),
        migrations.AlterField(
            model_name='company_e',
            name='Environmental_protection_action_investment',
            field=models.IntegerField(default='0', verbose_name='绿色信贷余额(亿元)'),
        ),
        migrations.AlterField(
            model_name='company_e',
            name='Greenhouse_gas_emissions',
            field=models.IntegerField(default='0', verbose_name='温室气体排放量(吨)'),
        ),
        migrations.AlterField(
            model_name='company_e',
            name='value',
            field=models.IntegerField(default='0', verbose_name='资产(亿元)'),
        ),
        migrations.AlterField(
            model_name='company_e',
            name='water_consumption',
            field=models.IntegerField(default='0', verbose_name='耗水量(吨)'),
        ),
        migrations.AlterField(
            model_name='company_g',
            name='value',
            field=models.IntegerField(default='0', verbose_name='资产(亿元)'),
        ),
        migrations.AlterField(
            model_name='company_s',
            name='value',
            field=models.IntegerField(default='0', verbose_name='资产(亿元)'),
        ),
    ]
