# Generated by Django 4.1.1 on 2022-10-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_e_cut_cod_company_e_cut_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='media/default/476c58d89ec6c6066d7ae241d97a1e2e.jpeg', upload_to='company/%Y/%m', verbose_name='封面图'),
        ),
    ]
