# Generated by Django 4.1.1 on 2022-10-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='default/476c58d89ec6c6066d7ae241d97a1e2e.jpeg', upload_to='company/%Y/%m', verbose_name='封面图'),
        ),
    ]
